let itemData = [
    {
        itemName: "iPhone 14 Pro",
        img: "/Media/iphone14pro.png",
        price: "$999",
        p1: "Brighter 6.1” Super Retina XDR display¹ featuring Always-On, which keeps your info at a glance",
        p2: "Dynamic Island, a magical new way to interact with iPhone",
        p3: "48MP Main camera with an advanced quad-pixel sensor for up to 4x the resolution",
        p4: "A16 Bionic chip — superfast and superefficient for amazing all-day battery life",
    },
    {
        itemName: "iPhone 14",
        img: "/Media/iphone14.png",
        price: "$799",
        p1: "6.1-inch Super Retina XDR display¹ that’s sharp, vibrant, and bright",
        p2: "Awesome all-day battery life with up to 20 hours video playback²",
        p3: "A new Main camera and improved image processing for even more sensational shots in all kinds of light",
        p4: "A15 Bionic, the same superspeedy chip that’s in iPhone 13 Pro",
    },
    {
        itemName: "iPhone 13",
        img: "/Media/iphone13.png",
        price: "$699",
        p1: "6.1-inch Super Retina XDR display¹",
        p2: "Advanced dual-camera system for incredible low-light photos and videos",
        p3: "A15 Bionic with 4-core GPU for lightning-fast performance",
        p4: "Ceramic Shield, tougher than any smartphone glass. And water resistance.²",
    },
    {
        itemName: "iPhone 12",
        img: "/Media/iphone12.png",
        price: "$599",
        p1: "6.1-inch Super Retina XDR displayfootnote¹ for great contrast and incredible color accuracy",
        p2: "Advanced dual-camera system with Night mode and Dolby Vision HDR recording",
        p3: "Superpowerful A14 Bionic chip",
        p4: "",
    },
    {
        itemName: "iPad Pro",
        img: "/Media/ipadpro11.png",
        price: "$799",
        p1: "The Apple M2 chip powers a massive leap in performance for pro workflows and all-day battery life¹",
        p2: "11-inch Liquid Retina displayfootnote² with ProMotion, True Tone, and P3 wide color",
        p3: "Pro cameras with LiDAR Scanner, and Ultra Wide front camera with Center Stage",
        p4: "Wi-Fi 6E for the fastest Wi-Fi connections. And 5G for superfast downloads and high-quality streaming.³",
    },
    {
        itemName: "iPad Air",
        img: "/Media/ipadair.jpg",
        price: "$599",
        p1: "Apple M1 chip powers next-level performance and all-day battery lifefootnote¹",
        p2: "10.9-inch Liquid Retina display delivers an immersive viewing experiencefootnote²",
        p3: "12MP Ultra Wide front camera with Center Stage for more natural video calls",
        p4: "Get blazing-fast 5G on cellular models and superfast Wi-Fi with Wi-Fi 6footnote³",
    },
    {
        itemName: "iPad 10th Gen",
        img: "/Media/ipad10.png",
        price: "$449",
        p1: "The A14 Bionic chip lets you run multiple apps and work smoothly between them",
        p2: "All-screen design with 10.9-inch Liquid Retina display¹ delivers an amazing viewing experience",
        p3: "Landscape 12MP Ultra Wide front camera with Center Stage for a great video calling experience",
        p4: "Stay connected with superfast Wi-Fi 6 and 5G wireless²",
    },
    {
        itemName: "iPad 9th Gen",
        img: "/Media/ipad9.png",
        price: "$329",
        p1: "The A13 Bionic chip with Neural Engine makes everything you do incredibly responsive",
        p2: "10.2-inch Retina display with True Tone for incredible detail and vivid colors",
        p3: "12MP Ultra Wide front camera with Center Stage for great video calls",
        p4: "Fast connection with 802.11ac Wi-Fi and Gigabit-class LTE cellular datafootnote¹",
    },
    {
        itemName: "Macbook Pro 14''",
        img: "/Media/macbook14.png",
        price: "$1999",
        p1: "New Apple M1 Pro and M1 Max chips deliver incredible performance",
        p2: "Up to 17 hours of battery life,footnote¹ thanks to the efficiency of Apple silicon",
        p3: "Liquid Retina XDR display features extreme dynamic range and incredible contrast ratio",
        p4: "New 1080p FaceTime HD camera, high-fidelity six-speaker sound system, and studio-quality mic array",
    },
    {
        itemName: "Macbook Pro 13''",
        img: "/Media/macbook13.png",
        price: "$1299",
        p1: "Get more done faster with the next-generation Apple M2 chip and an active cooling system that sustains pro levels of performance",
        p2: "Go all day and into the night with up to 20 hours of battery lifefootnote¹",
        p3: "Retina display with 500 nits of brightness delivers vibrant colors and incredible detail",
        p4: "Two Thunderbolt ports let you connect and power high-speed accessories",
    },
    {
        itemName: "Macbook Air M2",
        img: "/Media/macbookairm2.jpg",
        price: "$1199",
        p1: "All-new strikingly thin design so you can work, play, or create just about anything — anywhere",
        p2: "Get more done faster with the next-generation Apple M2 chip — and go all day and into the night with up to 18 hours of battery life¹",
        p3: "13.6-inch Liquid Retina display with 500 nits of brightness makes text and images look brilliant, with vivid detailfootnote²",
        p4: "Everything looks sharp and sounds great with a 1080p FaceTime HD camera, three-mic array, and four-speaker sound system with Spatial Audio",
    },
    {
        itemName: "Macbook Air M1",
        img: "/Media/macbookairm1.png",
        price: "$999",
        p1: "Apple M1 chip delivers powerful CPU, GPU, and machine learning performance",
        p2: "Up to 18 hours of battery life so you can go longer than everFootnote1",
        p3: "Retina display with vibrant colors and incredible detail",
        p4: "Superfast SSD storage opens apps and files in an instant",
    },
    {
        itemName: "Apple Watch Ultra",
        img: "/Media/watchultra.png",
        price: "$799",
        p1: "The ultra tough 49mm titanium case with new Action button strikes a balance with weight, ruggedness, and corrosion resistance",
        p2: "Biggest, brightest Always-On Retina display that’s readable in the harshest conditions",
        p3: "Precision dual-frequency GPS provides accurate location for calculating distance, pace, and route maps",
        p4: "Up to 36 hours¹ of battery life, and up to 60 hours² on low power settings",
    },
    {
        itemName: "Apple Watch Series 8",
        img: "/Media/watch8.jpg",
        price: "$399",
        p1: "Bright Always-On Retina display with an expansive edge-to-edge design",
        p2: "Introducing temperature sensing¹, which provides retrospective ovulation estimates and advanced cycle tracking² features",
        p3: "Take an ECG³ to check for AFib⁴ — anytime, anywhere",
        p4: "Innovative safety features including Fall Detection, Emergency SOS⁵, and now Crash Detection",
    },
    {
        itemName: "Apple Watch SE",
        img: "/Media/watchse.png",
        price: "$249",
        p1: "20% faster than Apple Watch SE (1st generation) with the new S8 SiP¹",
        p2: "Innovative safety features including Fall Detection, Emergency SOS², and now Crash Detection",
        p3: "Experience new ways to train with the enhanced Workout app",
        p4: "Track your sleep stages with the Sleep app, and check your heart rate anytime",
    },
    {
        itemName: "Apple Watch Hermes",
        img: "/Media/watchhermes.jpg",
        price: "$1229",
        p1: "Exclusive Hermès bands and watch faces",
        p2: "Bright Always-On Retina display with an expansive edge-to-edge design",
        p3: "Introducing temperature sensing¹, which provides retrospective ovulation estimates and advanced cycle tracking² features",
        p4: "Take an ECG³ to check for AFib⁴ — anytime, anywhere",
    },
];
